title: "Fabian Müller, PhD"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Grundlegende Einstellungen
name: "Fabian Müller"
description: "Social psychologist working at the intersection of education, inequality, and policy."
locale: "en"

# Seitenelemente
logo: false

# Navigation
header:
  background: "#111"
  text_color: "#fff"
  nav:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv/
    - title: "Research"
      url: /research/
    - title: "Contact"
      url: /contact/

# Footer
footer:
  text: "© 2025 Fabian Müller – All rights reserved."
  background: "#111"
  text_color: "#fff"
  links: []

# Plugins (wichtig für Navigation etc.)
plugins:
  - jekyll-include-cache
