remote_theme: "mmistakes/minimal-mistakes@4.24.0"

header:
  background: "#111"  # dunkel
  text_color: "#fff"
  logo: false
  title: "Fabian Müller, PhD"
  nav:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv/
    - title: "Research"
      url: /research/
    - title: "Contact"
      url: /contact/

footer:
  links: []
  text: "© 2025 Fabian Müller – All rights reserved."
  background: "#111"
  text_color: "#fff"
