title: "Fabian Müller, PhD"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"


# Grundlegende Einstellungen
name: "Fabian Müller"
description: "Social psychologist working at the intersection of education, inequality, and policy."
locale: "en"

# Navigation für Minimal Mistakes (DOKU-BEISPIEL)
navigation:
  main:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Contact"
    url: /contact/


# Navigation für den Header
#main:
#  - title: "Home"
#    url: /
#  - title: "CV"
#    url: /cv/
#  - title: "Research"
#    url: /research/
#  - title: "Contact"
#    url: /contact/
    
# Navigation (Header oben)
# header:
#  background: "#111"
#  text_color: "#fff"
#  logo: false
#  title: "Fabian Müller, PhD"
#  nav:
#    - title: "Home"
#      url: /
#    - title: "CV"
#      url: /cv/
#    - title: "Research"
#      url: /research/
#    - title: "Contact"
#      url: /contact/

footer:
  text: ""
  background: "#111"
  text_color: "#cccccc"
  links: []
  powered_by: false



# Plugins (wichtig für Navigation etc.)
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap

# Sass (damit dein eigenes CSS greift)
sass:
  style: compressed

# Custom CSS (falls du eigene CSS-Datei einbindest)
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"

atom_feed:
  hide: true

