title: "Fabian Müller, PhD"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"


# Grundlegende Einstellungen
name: "Fabian Müller"
description: "Social psychologist working at the intersection of education, inequality, and policy."
locale: "en"

# Das ist der wichtige Teil!
navigation:
  main:
    - title: "CV"
      url: /cv/
    - title: "Research & Policy"
      url: /research/
    - title: "Publications"
      url: /publications/
    - title: "Teaching"
      url: /teaching/
    - title: "Contact"
      url: /contact/



footer:
  text: ""
  background: "#111"
  text_color: "#cccccc"
  links: []
  powered_by: false
  custom: custom



# Plugins (wichtig für Navigation etc.)
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap

# Sass (damit dein eigenes CSS greift)
sass:
  style: compressed

# Custom CSS (falls du eigene CSS-Datei einbindest)
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"

atom_feed:
  hide: true

# Eigener Header-Include
header:
  custom: custom-header
